# Generated by Django 4.2.5 on 2023-09-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone3',
            field=models.CharField(default='', max_length=50),
        ),
    ]
