# Generated by Django 4.2.5 on 2023-09-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_record_phone2_alter_record_phone3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
