# Generated by Django 4.2.5 on 2023-09-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_record_phone2_alter_record_phone3'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
